// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *CV Page → Key Skills*
 */
export interface CvPageDocumentDataKeySkillsItem {
  /**
   * Tech field in *CV Page → Key Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.key_skills[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"tech">;
}

/**
 * Item in *CV Page → Jobs*
 */
export interface CvPageDocumentDataJobsItem {
  /**
   * Job field in *CV Page → Jobs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.jobs[].job
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  job: prismic.ContentRelationshipField<"job">;
}

/**
 * Item in *CV Page → Education*
 */
export interface CvPageDocumentDataEducationItem {
  /**
   * Edu field in *CV Page → Education*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.education[].edu
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  edu: prismic.ContentRelationshipField<"education">;
}

type CvPageDocumentDataSlicesSlice = never;

/**
 * Content for CV Page documents
 */
interface CvPageDocumentData {
  /**
   * Page Title field in *CV Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * PDF field in *CV Page*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.pdf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pdf: prismic.LinkToMediaField;

  /**
   * Summary field in *CV Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Key Skills field in *CV Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.key_skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  key_skills: prismic.GroupField<Simplify<CvPageDocumentDataKeySkillsItem>>;

  /**
   * Secondary Skills field in *CV Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.secondary_skills
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_skills: prismic.RichTextField;

  /**
   * Jobs field in *CV Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.jobs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  jobs: prismic.GroupField<Simplify<CvPageDocumentDataJobsItem>>;

  /**
   * Education field in *CV Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.education[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  education: prismic.GroupField<Simplify<CvPageDocumentDataEducationItem>>;

  /**
   * Slice Zone field in *CV Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: cv_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CvPageDocumentDataSlicesSlice>;
}

/**
 * CV Page document from Prismic
 *
 * - **API ID**: `cv_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CvPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CvPageDocumentData>,
    "cv_page",
    Lang
  >;

/**
 * Item in *Demo → Tech Stack*
 */
export interface DemoDocumentDataTechStackItem {
  /**
   * Tech field in *Demo → Tech Stack*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.tech_stack[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"tech">;
}

/**
 * Content for Demo documents
 */
interface DemoDocumentData {
  /**
   * Title field in *Demo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Demo*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Picture field in *Demo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Tech Stack field in *Demo*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.tech_stack[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tech_stack: prismic.GroupField<Simplify<DemoDocumentDataTechStackItem>>;

  /**
   * GitHub field in *Demo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;

  /**
   * Demo field in *Demo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: demo.demo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  demo: prismic.LinkField;
}

/**
 * Demo document from Prismic
 *
 * - **API ID**: `demo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DemoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DemoDocumentData>, "demo", Lang>;

/**
 * Item in *Demo Page → Demos*
 */
export interface DemoPageDocumentDataDemosItem {
  /**
   * Demo field in *Demo Page → Demos*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_page.demos[].demo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  demo: prismic.ContentRelationshipField<"demo">;
}

type DemoPageDocumentDataSlicesSlice = never;

/**
 * Content for Demo Page documents
 */
interface DemoPageDocumentData {
  /**
   * Page Title field in *Demo Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Demos field in *Demo Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_page.demos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  demos: prismic.GroupField<Simplify<DemoPageDocumentDataDemosItem>>;

  /**
   * Slice Zone field in *Demo Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DemoPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Demo Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: demo_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Demo Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: demo_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Demo Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: demo_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Demo Page document from Prismic
 *
 * - **API ID**: `demo_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DemoPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DemoPageDocumentData>,
    "demo_page",
    Lang
  >;

/**
 * Content for Education documents
 */
interface EducationDocumentData {
  /**
   * Degree field in *Education*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.degree
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  degree: prismic.KeyTextField;

  /**
   * Institution field in *Education*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.institution
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  institution: prismic.KeyTextField;

  /**
   * Institution Logo field in *Education*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: education.institution_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  institution_logo: prismic.ImageField<never>;

  /**
   * Date From field in *Education*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: education.date_from
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_from: prismic.DateField;

  /**
   * Date To field in *Education*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: education.date_to
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_to: prismic.DateField;

  /**
   * Description field in *Education*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Education document from Prismic
 *
 * - **API ID**: `education`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EducationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EducationDocumentData>,
    "education",
    Lang
  >;

/**
 * Item in *Home Page → Key Skills*
 */
export interface HomepageDocumentDataKeySkillsItem {
  /**
   * Tech field in *Home Page → Key Skills*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.key_skills[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"tech">;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Home Page documents
 */
interface HomepageDocumentData {
  /**
   * Headline field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.headline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * Intro field in *Home Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  intro: prismic.RichTextField;

  /**
   * Picture field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Key Skills field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.key_skills[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  key_skills: prismic.GroupField<Simplify<HomepageDocumentDataKeySkillsItem>>;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Job → Tech*
 */
export interface JobDocumentDataTechItem {
  /**
   * Tech field in *Job → Tech*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: job.tech[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"tech">;
}

/**
 * Item in *Job → Projects*
 */
export interface JobDocumentDataProjectsItem {
  /**
   * Project field in *Job → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: job.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Content for Job documents
 */
interface JobDocumentData {
  /**
   * Employer field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.employer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  employer: prismic.KeyTextField;

  /**
   * Employer Logo field in *Job*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: job.employer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  employer_logo: prismic.ImageField<never>;

  /**
   * Employer Website field in *Job*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: job.employer_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  employer_website: prismic.LinkField;

  /**
   * Employer Summary field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.employer_summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  employer_summary: prismic.KeyTextField;

  /**
   * Industry field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.industry
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  industry: prismic.KeyTextField;

  /**
   * Job Title field in *Job*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  job_title: prismic.KeyTextField;

  /**
   * Type field in *Job*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: job.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<
    "Permanent" | "Contract" | "Spare Time Freelance" | "Volunteering"
  >;

  /**
   * Date Start field in *Job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.date_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_start: prismic.DateField;

  /**
   * Date End field in *Job*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job.date_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_end: prismic.DateField;

  /**
   * Description field in *Job*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tech field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.tech[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tech: prismic.GroupField<Simplify<JobDocumentDataTechItem>>;

  /**
   * Projects field in *Job*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<JobDocumentDataProjectsItem>>;
}

/**
 * Job document from Prismic
 *
 * - **API ID**: `job`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<JobDocumentData>, "job", Lang>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Project → Tech*
 */
export interface ProjectDocumentDataTechItem {
  /**
   * Tech field in *Project → Tech*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tech[].tech
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tech: prismic.ContentRelationshipField<"tech">;
}

/**
 * Item in *Project → Gallery (Desktop)*
 */
export interface ProjectDocumentDataGalleryItem {
  /**
   * Picture field in *Project → Gallery (Desktop)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<"large">;
}

/**
 * Item in *Project → Gallery (Mobile)*
 */
export interface ProjectDocumentDataGalleryMobileItem {
  /**
   * Picture field in *Project → Gallery (Mobile)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery_mobile[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Item in *Project → Gallery (Before)*
 */
export interface ProjectDocumentDataGalleryBeforeItem {
  /**
   * Picture field in *Project → Gallery (Before)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery_before[].picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Project*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Employer field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.employer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  employer: prismic.ContentRelationshipField<"job">;

  /**
   * Logo Override field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.logo_override
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_override: prismic.ImageField<never>;

  /**
   * Intro field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  intro: prismic.KeyTextField;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Tech field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.tech[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tech: prismic.GroupField<Simplify<ProjectDocumentDataTechItem>>;

  /**
   * Gallery (Desktop) field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<ProjectDocumentDataGalleryItem>>;

  /**
   * Gallery (Mobile) field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery_mobile[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_mobile: prismic.GroupField<
    Simplify<ProjectDocumentDataGalleryMobileItem>
  >;

  /**
   * Gallery (Before) field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery_before[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_before: prismic.GroupField<
    Simplify<ProjectDocumentDataGalleryBeforeItem>
  >;

  /**
   * Link field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *Project Page → Projects*
 */
export interface ProjectPageDocumentDataProjectsItem {
  /**
   * Project field in *Project Page → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

type ProjectPageDocumentDataSlicesSlice = never;

/**
 * Content for Project Page documents
 */
interface ProjectPageDocumentData {
  /**
   * Page Title field in *Project Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Projects field in *Project Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<ProjectPageDocumentDataProjectsItem>>;

  /**
   * Slice Zone field in *Project Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice> /**
   * Meta Description field in *Project Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Project Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Project Page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectPageDocumentData>,
    "project_page",
    Lang
  >;

/**
 * Content for Tech documents
 */
interface TechDocumentData {
  /**
   * Name field in *Tech*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tech.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Icon field in *Tech*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tech.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Non-Distinct field in *Tech*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: tech.nondistinct
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  nondistinct: prismic.BooleanField;
}

/**
 * Tech document from Prismic
 *
 * - **API ID**: `tech`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TechDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TechDocumentData>, "tech", Lang>;

export type AllDocumentTypes =
  | CvPageDocument
  | DemoDocument
  | DemoPageDocument
  | EducationDocument
  | HomepageDocument
  | JobDocument
  | PageDocument
  | ProjectDocument
  | ProjectPageDocument
  | TechDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CvPageDocument,
      CvPageDocumentData,
      CvPageDocumentDataKeySkillsItem,
      CvPageDocumentDataJobsItem,
      CvPageDocumentDataEducationItem,
      CvPageDocumentDataSlicesSlice,
      DemoDocument,
      DemoDocumentData,
      DemoDocumentDataTechStackItem,
      DemoPageDocument,
      DemoPageDocumentData,
      DemoPageDocumentDataDemosItem,
      DemoPageDocumentDataSlicesSlice,
      EducationDocument,
      EducationDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataKeySkillsItem,
      HomepageDocumentDataSlicesSlice,
      JobDocument,
      JobDocumentData,
      JobDocumentDataTechItem,
      JobDocumentDataProjectsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataTechItem,
      ProjectDocumentDataGalleryItem,
      ProjectDocumentDataGalleryMobileItem,
      ProjectDocumentDataGalleryBeforeItem,
      ProjectPageDocument,
      ProjectPageDocumentData,
      ProjectPageDocumentDataProjectsItem,
      ProjectPageDocumentDataSlicesSlice,
      TechDocument,
      TechDocumentData,
      AllDocumentTypes,
    };
  }
}
